### ISSUE TITLE
一些想法的记录

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-moe#1]
- 体重很大看起来却不胖 （“骨架重“?，背包，还是漏的背包）
- 经常在主人工作的时候撒娇（容易罢工）
- 中文特别好（本地化工作）同时神任其他语言（多语言支持）
- 对多架构的支持（处理器气球，cpu 架构名）
- 以前是 ___，现在不问世事，文静（结合以前在 Linux 吧的黑历史和现在的宣传程度）
- 怕冷，所以衣服穿的比较多（buildbot 机器）

**Comment by misaka4e21** [comment]
还有经常炫耀自己的底裤（风纪会
