### ISSUE TITLE
果冻女装！俄式套娃！

### ISSUE THREAD

**Issue by neruthes** [AOSC-Dev/aosc-moe#2]
![ASOC Moe 1](https://user-images.githubusercontent.com/2139261/56853634-26a62680-691a-11e9-977f-148e00625979.png)
![ASOC Moe 2](https://user-images.githubusercontent.com/2139261/56853635-273ebd00-691a-11e9-87c5-adcf805207a2.png)

**Comment by misaka4e21** [comment]
主题曲：
白特首要连任好不好呀？
若女装我们全都支持他！
从康乃迪克到上海川沙，
可爱的少女A2最强大。
（副歌）
安徽的同志们……
